name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main
          - name: Checkout repository
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.REGISTRY_TOKEN}}
              
          - name: 'Build Inventory Image'
            run: |
              make build-image push-image
