name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: self-hosted
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main
          - name: Checkout repository
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.REGISTRY_TOKEN}}
              
          - name: 'Build Inventory Image'
            run: |
              make build-image push-image

      cd:
        name: CD
        needs: push-store-image
        if: github.actor != 'github-actions[bot]' # Prevents loop by ignoring commits from GitHub Actions bot
        runs-on: self-hosted
    
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    
        - uses: mikefarah/yq@master
          with: 
            cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml
    
    
        - run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -am "update version $VERSION"
            git push